# Generated by Django 3.1.3 on 2020-11-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabtaguzari',
            name='email',
        ),
    ]
