# Generated by Django 3.1.3 on 2020-11-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_rabtaguzari_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabtaguzari',
            name='desc',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
        migrations.AddField(
            model_name='rabtaguzari',
            name='email',
            field=models.CharField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AddField(
            model_name='rabtaguzari',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=122),
        ),
        migrations.AddField(
            model_name='rabtaguzari',
            name='phone',
            field=models.CharField(default='DEFAULT VALUE', max_length=12),
        ),
    ]
