# Generated by Django 3.1.3 on 2020-11-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201127_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabtaguzari',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
