# Generated by Django 3.1.3 on 2020-11-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201127_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabtaguzari',
            name='desc',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='email',
            field=models.CharField(default='default', max_length=122),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='name',
            field=models.CharField(default='default', max_length=122),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='phone',
            field=models.CharField(default='default', max_length=122),
        ),
    ]
