# Generated by Django 3.1.3 on 2020-11-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201127_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabtaguzari',
            name='email',
            field=models.CharField(blank=True, default='default', max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='name',
            field=models.CharField(blank=True, default='default', max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='phone',
            field=models.CharField(blank=True, default='default', max_length=122, null=True),
        ),
    ]
