# Generated by Django 3.1.3 on 2020-11-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201127_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabtaguzari',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='name',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
