# Generated by Django 3.1.3 on 2020-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201128_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabtaguzari',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rabtaguzari',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
