# Generated by Django 3.1.3 on 2020-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20201129_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='sno',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='id',
            field=models.AutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
