# Generated by Django 3.1.3 on 2020-11-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20201130_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='id',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
