# Generated by Django 3.1.3 on 2021-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank='true', null='true', upload_to=''),
            preserve_default='true',
        ),
    ]
