# Generated by Django 3.1.3 on 2021-02-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank='true', null='true', upload_to='media/images'),
        ),
    ]
